### ISSUE TITLE
Talen Suggestie:

### ISSUE THREAD

**Issue by DataLiontje** [Hebbinkpro/betterBroadcast#3]
Wat je zou kunnen doen ipv: overal if statements is gewoon 2 files maken met alle teksten een: eng.yml en een nl.yml

Die zijn dan ook weer configurable zonder dat je de plugin hoeft aan te passen om tekst te hoeven te veranderen.

**Comment by Hebbinkpro** [comment]
ga ik aan werken, bedankt voor de tip
